spring.application.name=backend

logging.level.org.springframework.security=DEBUG

# MongoDB configuration
spring.data.mongodb.uri=mongodb://localhost:27017/
spring.data.mongodb.auto-index-creation=true

# Gson configuration
spring.gson.strictness=LENIENT
spring.data.mongodb.database=backend

server.port=8080
spring.server.host=localhost

# # AWS credentials
cloud.aws.accessKey=
cloud.aws.secretKey=
cloud.aws.region=ap-south-1

azure.client-id="2a76887e-ed46-4e78-82f4-0a431ad4a53d"
azure.client-secret="f5eae055-d697-419b-b4cd-07157698bf04"
azure.tenant-id= 2e859973-d2a7-469c-b8f4-0d1c377f7b33
azure.subscription-id= 406a7606-9b1e-42d1-85cd-83763f6a45b7

# GCP credentials
cloud.gcp.serviceAccountKey = "C:\Users\yuvas\Downloads\srigopinath-angamuthuraja.json"

ai.service.url=https://api.openai.com/v1
ai.service.key=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


spring.security.user.name=admin
spring.security.user.password=admin123
spring.main.allow-bean-definition-overriding=true