spring.application.name=backend

logging.level.org.springframework.security=DEBUG

# MongoDB configuration
spring.data.mongodb.uri=mongodb://localhost:27017/
spring.data.mongodb.auto-index-creation=true

# Gson configuration
spring.gson.strictness=LENIENT
spring.data.mongodb.database=backend

server.port=8080

# # AWS credentials
cloud.aws.accessKey=
cloud.aws.secretKey=
cloud.aws.region=ap-south-1


azure.client-id=
azure.client-secret=
azure.tenant-id=
azure.subscription-id=


# GCP credentials
cloud.gcp.serviceAccountKey=

ai.service.url=https://api.openai.com/v1
ai.service.key=


spring.security.user.name=admin
spring.security.user.password=admin123
spring.main.allow-bean-definition-overriding=true