spring.application.name=backend

logging.level.org.springframework.security=DEBUG

# MongoDB configuration
spring.data.mongodb.uri=mongodb://localhost:27017/
spring.data.mongodb.auto-index-creation=true

# Gson configuration
spring.gson.strictness=LENIENT
spring.data.mongodb.database=backend

server.port=8080

# AWS credentials
cloud.aws.accessKey=
cloud.aws.secretKey=
cloud.aws.region=ap-south-1

azure.client-id=
azure.client-secret=
azure.tenant-id=
azure.subscription-id=

# GCP credentials
cloud.gcp.serviceAccountKey=
cloud.gcp.projectId=

# cloud.gcp.serviceAccountKey=C:\\Users\\yuvas\\Downloads\\our-vigil-470916-i8-9f19bac8856a.json
# cloud.gcp.projectId=our-vigil-470916-i8

ai.service.url=https://api.openai.com/v1
ai.service.key=
openai.api.key=

azure.openai.api.key=
azure.openai.model=gpt-4  # Or your preferred model version
azure.openai.deployment.id=gpt-4-2  # This should match the deployment name you used in Azure

spring.security.user.name=admin
spring.security.user.password=admin123
spring.main.allow-bean-definition-overriding=true
